-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 19:06:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

create database pixelstore_DB;
use pixelstore_DB;

-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `descripcion_product` TEXT NULL,
  `stock` INT NULL,
  `estado` TINYINT NULL,
  `marca` VARCHAR(100) NULL,
  `imagen_product` VARCHAR(200) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `pixelstore_DB`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_Usuario` VARCHAR(100) NULL,
  `correo_Usuario` VARCHAR(100) NULL,
  `contrasenia_Usuario` VARCHAR(255) NULL,
  `rol` VARCHAR(20) NULL,
  `estado_Usuario` TINYINT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `correo_Usuario_UNIQUE` (`correo_Usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `fk_Carrito_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `pixelstore_DB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Detalle_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Detalle_carrito` (
  `idDetalle_carrito` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idDetalle_carrito`),
  INDEX `fk_Detalle_carrito_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Detalle_carrito_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `pixelstore_DB`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_carrito_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `pixelstore_DB`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Venta_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Venta_Usuario` (
  `idVenta_Usuario` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATETIME NULL,
  `total` DECIMAL(10,2) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVenta_Usuario`),
  INDEX `fk_Venta_Usuario_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Usuario_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `pixelstore_DB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Detalle_Venta_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Detalle_Venta_Usuario` (
  `idDetalle_Venta_Usuario` INT NOT NULL AUTO_INCREMENT,
  `cantidades` INT NOT NULL,
  `precio_unidad` DECIMAL(10,2) NULL,
  `subTotal_Venta` DECIMAL(10,2) NULL,
  `Venta_Usuario_idVenta_Usuario` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Venta_Usuario`),
  INDEX `fk_Detalle_Venta_Usuario_Venta_Usuario1_idx` (`Venta_Usuario_idVenta_Usuario` ASC) VISIBLE,
  INDEX `fk_Detalle_Venta_Usuario_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Venta_Usuario_Venta_Usuario1`
    FOREIGN KEY (`Venta_Usuario_idVenta_Usuario`)
    REFERENCES `pixelstore_DB`.`Venta_Usuario` (`idVenta_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Venta_Usuario_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `pixelstore_DB`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Favoritos` (
  `idFavoritos` INT NOT NULL AUTO_INCREMENT,
  `fecha_agregada` DATETIME NULL,
  `Productos_idProductos` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idFavoritos`),
  INDEX `fk_Favoritos_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Favoritos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Favoritos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `pixelstore_DB`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `pixelstore_DB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pixelstore_DB`.`Resenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pixelstore_DB`.`Resenia` (
  `idResenia` INT NOT NULL AUTO_INCREMENT,
  `nombre_resenia` VARCHAR(100) NULL,
  `comentario` VARCHAR(255) NULL,
  `calificacion` INT NULL,
  `fecha_comentario` DATETIME NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idResenia`),
  INDEX `fk_Resenia_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Resenia_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `pixelstore_DB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
